apiVersion: v1
kind: Service 
metadata:
  name: myflask-lb-service-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb   
spec:
  type: LoadBalancer 
  selector:
    app: myflask
  ports: 
    - name: http
      port: 80 
      targetPort: 5000 

