apiVersion: v1
kind: Service
metadata:
  name: {{ include "obz-flask-app.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.service.annotations.lbType }}
  labels:
    {{- include "obz-flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "obz-flask-app.selectorLabels" . | nindent 4 }}
