module "rds" {
  identifier = var.rds_name
  source  = "terraform-aws-modules/rds/aws"
  engine = var.rds_engine
  engine_version = var.rds_postgres_version
  instance_class = var.rds_instance_class
  allocated_storage = var.rds_storage_size
  db_name = var.rds_db_name
  username = var.rds_username
  password = var.rds_password 
  skip_final_snapshot = true  
  publicly_accessible = var.rds_publicly_accessible
  vpc_security_group_ids = var.vpc_security_group_ids
  multi_az = var.rds_muti_az
  db_subnet_group_name = var.database_subnet_group_name
  family  = var.rds_family
  major_engine_version = var.rds_major_engine_version 
  manage_master_user_password = var.rds_manage_password
}