name: 'Terraform Infrastrucure Deployment'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  deploy-infra:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    outputs: 
      RDS_ENDPOINT: ${{ steps.extract.outputs.RDS_ENDPOINT }}
      EKS_CLUSTER_NAME:  ${{ steps.extract.outputs.EKS_CLUSTER_NAME }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_VALUE }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Deploy Terraform Infra
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        make deploy-infra
        # export rds endpoint to be used in deployment
        DB_ENDPOINT=$(cat deployment-results.txt | grep 'rds_postsgres_db_endpoint' | sed 's/:5432//; s/.*= "//; s/"//')
        echo "RDS_ENDPOINT=$DB_ENDPOINT"
        echo "RDS_ENDPOINT=$DB_ENDPOINT" > workflow-artifact.txt

        CLUSTER_NAME=$(cat deployment-results.txt | grep 'cluster_name' | sed 's/cluster_name = "//' | sed 's/"//')
        echo "EKS_CLUSTER_NAME=$CLUSTER_NAME"
        echo "EKS_CLUSTER_NAME=$CLUSTER_NAME" >> workflow-artifact.txt
  #   - name: Upload infra artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: workflow-artifact
  #       path: workflow-artifact.txt

  # deploy-image:
  #   name: Deploy Image To ECR
  #   runs-on: ubuntu-latest
  #   needs: deploy-infra
  #   environment: dev
  #   outputs: 
  #     IMAGE_NAME: ${{ steps.extract.outputs.IMAGE_NAME }}
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: workflow-artifact
  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: ${{ secrets.AWS_REGION_VALUE }}
  #   - name: Login to Amazon ECR
  #     id: login-ecr
  #     uses: aws-actions/amazon-ecr-login@v1
  #   - name: Build, and tag image to Amazon ECR
  #     id: build-image
  #     env:
  #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #       IMAGE_TAG: ${{ github.sha }}
  #       ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
  #     run: 
  #       make build-image
  #   - name: Push image to Amazon ECR
  #     id: push-image
  #     env:
  #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #       IMAGE_TAG: ${{ github.sha }}
  #       ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
  #     run: | 
  #       make push-image
  #       IMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
  #       echo "IMAGE_NAME=$IMAGE_NAME"
  #       echo "IMAGE_NAME=$IMAGE_NAME" >> workflow-artifact.txt
  #       echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
  #       echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
  #   - name: Upload image artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: workflow-artifact
  #       path: workflow-artifact.txt

  # deploy-container:
  #   name: Deploy container to EKS
  #   runs-on: ubuntu-latest
  #   needs: deploy-image
  #   environment: dev
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: workflow-artifact
  #   - name: Extract artifact
  #     run: |
  #       cat workflow-artifact.txt
  #       set -a
  #       source workflow-artifact.txt
  #       set +a

  #       echo "$RDS_ENDPOINT"
  #       echo "$IMAGE_NAME"




    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION_VALUE }}
    # - name: Get kubectl
    #   run: |
    #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    #     echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
    #     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    #     kubectl version --client
    # - name: Initialize kubeconfig
    #   run: 
    #     aws eks --region ${{ secrets.AWS_REGION_VALUE }} update-kubeconfig --name 
    # - name: Create Manifests
    #   env:
    #     IMAGE_NAME: ${{ steps.extract.outputs.IMAGE_NAME }}
    #     RDS_ENDPOINT: ${{ steps.extract.outputs.RDS_ENDPOINT }}
    #   run: 
    #     make create-manifests
    # - name: deploy-container
    #   run: 
    #     make deploy-container




